version: '2.3'
services:
  bot:
    build:
      context: .
      target: bot
    volumes:
      - ./secret.toml:/app/secret.toml
    links:
      - redis:redis
  web:
    build:
      context: .
      target: web
    volumes:
      - ./secret.toml:/app/secret.toml
      - ./key.pem:/etc/app/key.pem
    links:
      - redis:redis
    ports:
      - 8000:8000
  redis:
    image: redis:6-alpine
